### ISSUE TITLE
Multiple errors when trying to build the project

### ISSUE THREAD

**Issue by migueltk** [ringtailsoftware/zig-minirv32#1]
**Following the instructions, in the command;**
   ```
   zig build && ./zig-out/bin/zigrv32ima linux.bin
   ```
This error shows;
```
    zig-minirv32-master\build.zig:12:19: error: no field or member function named 'standardReleaseOptions' in 'Build'
        const mode = b.standardReleaseOptions();
                     ~^~~~~~~~~~~~~~~~~~~~~~~
```
and errors like;
```
error: expected 1 argument, found 2
    var v = @intCast(u32, 23);
            ^~~~~~~~~~~~~~~~~
```
I have tried it with the versions of zig '0.10.1', '0.11.0' y '0.12.0-dev'.

I understand that there have been changes in the releases that make the code incompatible with these new versions.

Any solution?

Thank you for your work... best regards.
Miguel

**Comment by ringtailsoftware** [comment]
Looking at my notes, I think I last built this with zig-linux-aarch64-0.11.0-dev.1971+5a12d0070.tar.xz
You're right, there have been lots of changes to the build process. I will try to find sometime to look at this, but it may be a while. The Zig Discord channel is a great place to keep up to date with the latest changes to the build system

**Comment by ringtailsoftware** [comment]
It now builds on zig 0.13.0. The main emulator runs linux, hello and mandelbrot samples.
